name: Run Telegram Bot

on:
  workflow_dispatch:  # Allows manual run
  schedule:
    - cron: '0 * * * *'  # Runs every hour (change as needed)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Run Bot
        run: |
          npm start
